import base64
import io
import json
from pathlib import Path
import struct
import tempfile
import unittest
from unittest.mock import patch
import zipfile
import zlib

from PIL import Image, PngImagePlugin

import server


def dirty_png():
    metadata = PngImagePlugin.PngInfo()
    metadata.add_text('Software', 'AI image generator test fixture')
    metadata.add_itxt('XML:com.adobe.xmp', '<xmp>Generated by AI</xmp>')
    buf = io.BytesIO()
    Image.new('RGBA', (3, 4), (21, 42, 84, 126)).save(buf, 'PNG', pnginfo=metadata)
    raw = buf.getvalue()
    chunk = b'caBX' + b'c2pa-test-provenance'
    ca = struct.pack('>I', len(chunk) - 4) + chunk + struct.pack('>I', zlib.crc32(chunk))
    return raw[:-12] + ca + raw[-12:]


def png_chunks(raw):
    offset = 8
    while offset + 12 <= len(raw):
        length = struct.unpack_from('>I', raw, offset)[0]
        yield raw[offset + 4:offset + 8]
        offset += length + 12


class Request:
    def __init__(self):
        self.wfile = io.BytesIO()
        self.headers = {}
        self.status = None

    def json(self, code, body):
        self.status = code
        return code, body

    def send_response(self, code):
        self.status = code

    def send_header(self, key, value):
        self.headers[key] = value

    def end_headers(self):
        pass


class Reply(io.BytesIO):
    def __init__(self, raw, mime='application/json'):
        super().__init__(raw)
        self.headers = {'Content-Type': mime}


class ImageExportMetadataTests(unittest.TestCase):
    def setUp(self):
        self.raw = dirty_png()
        self.b64 = base64.b64encode(self.raw).decode('ascii')
        self.data_url = 'data:image/png;base64,' + self.b64
        temp = tempfile.TemporaryDirectory()
        self.addCleanup(temp.cleanup)
        self.directory = Path(temp.name)
        folder = patch.object(server, 'GALLERY_DIR', temp.name)
        folder.start()
        self.addCleanup(folder.stop)

    def assert_clean(self, raw):
        self.assertTrue(raw.startswith(b'\x89PNG\r\n\x1a\n'))
        self.assertTrue(set(png_chunks(raw)).isdisjoint({b'caBX', b'tEXt', b'iTXt', b'zTXt', b'eXIf'}))
        with Image.open(io.BytesIO(raw)) as result, Image.open(io.BytesIO(self.raw)) as source:
            self.assertEqual(result.convert('RGBA').tobytes(), source.convert('RGBA').tobytes())

    def test_zip_cleans_data_urls_gallery_files_and_fetched_images(self):
        stored = self.directory / 'existing.png'
        stored.write_bytes(self.raw)
        h = Request()
        with patch.object(server, 'fetch_image_bytes', return_value=(self.raw, 'image/png')) as fetch:
            server.Handler.handle_download_zip(h, {'items': [
                {'data': self.data_url, 'name': 'data URL'},
                {'id': 'existing', 'name': 'gallery'},
                {'url': 'https://example.invalid/generated.png', 'name': 'URL'},
            ]})
        self.assertEqual(h.status, 200)
        self.assertEqual(h.headers['Content-Type'], 'application/zip')
        fetch.assert_called_once()
        with zipfile.ZipFile(io.BytesIO(h.wfile.getvalue())) as archive:
            self.assertEqual(len(archive.namelist()), 3)
            for name in archive.namelist():
                self.assert_clean(archive.read(name))
        self.assertEqual(stored.read_bytes(), self.raw, 'Downloading must not rewrite an existing original.')

    def test_zip_invalid_image_returns_error_without_partial_download(self):
        h = Request()
        code, body = server.Handler.handle_download_zip(h, {'items': [
            {'data': self.data_url},
            {'data': 'data:image/png;base64,' + base64.b64encode(b'not an image').decode()},
        ]})
        self.assertEqual(code, 400)
        self.assertIn('metadata ảnh thứ 2', body['error'])
        self.assertEqual(h.wfile.getvalue(), b'')
        self.assertNotIn('Content-Disposition', h.headers)

    def test_save_media_cleans_image_and_saves_png(self):
        url, kind, raw = server.save_media_file(self.data_url)
        self.assertEqual(kind, 'image')
        self.assertTrue(url.endswith('.png'))
        self.assert_clean(raw)
        self.assertEqual((self.directory / url.rsplit('/', 1)[-1]).read_bytes(), raw)
        buf = io.BytesIO()
        exif = Image.Exif()
        exif[305] = 'AI provider'
        Image.new('RGB', (2, 2), 'red').save(buf, 'JPEG', exif=exif)
        jpeg_url = 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode()
        url, kind, raw = server.save_media_file(jpeg_url)
        self.assertTrue(url.endswith('.png'))
        with Image.open(io.BytesIO(raw)) as image:
            self.assertEqual(image.format, 'PNG')
            self.assertFalse(image.getexif())

    def test_save_media_keeps_video_bytes_and_rejects_invalid_image(self):
        video = b'video fixture: keep metadata and bytes unchanged'
        url, kind, raw = server.save_media_file('data:video/mp4;base64,' + base64.b64encode(video).decode())
        self.assertEqual(kind, 'video')
        self.assertTrue(url.endswith('.mp4'))
        self.assertEqual(raw, video)
        self.assertEqual((self.directory / url.rsplit('/', 1)[-1]).read_bytes(), video)
        self.assertEqual(server.save_media_file('data:image/png;base64,bm90YW5pbWFnZQ=='), (None, None, None))

    def test_cutout_provider_cleans_every_response_shape(self):
        responses = [
            [Reply(self.raw, 'image/png')],
            [Reply(json.dumps({'data': {'imageBase64': self.b64}}).encode())],
            [Reply(json.dumps({'data': {'imageUrl': 'https://example.invalid/cutout.png'}}).encode()), Reply(self.raw, 'image/png')],
        ]
        for replies in responses:
            with self.subTest(response_shape=len(replies)), patch.object(server, 'CUTOUTPRO_KEY', 'fixture'), \
                    patch.object(server.urllib.request, 'urlopen', side_effect=replies):
                self.assert_clean(server.remove_bg_cutoutpro(b'input fixture'))

    def test_cutout_provider_does_not_return_unclean_invalid_output(self):
        with patch.object(server, 'CUTOUTPRO_KEY', 'fixture'), \
                patch.object(server.urllib.request, 'urlopen', return_value=Reply(b'bad output', 'image/png')):
            with self.assertRaises(ValueError):
                server.remove_bg_cutoutpro(b'input fixture')

    def test_upscale_cleans_output_including_passthrough_fallback(self):
        for method, function in [('ai', 'ai_upscale_png'), ('lanczos', 'upscale_png')]:
            with self.subTest(method=method), patch.object(server, function, return_value=self.raw):
                code, body = server.Handler.handle_upscale(Request(), {'image': self.b64, 'method': method})
                self.assertEqual(code, 200)
                self.assert_clean(base64.b64decode(body['image']))

    def test_remove_bg_cleans_result_before_return_and_gallery(self):
        with patch.object(server, 'strip_background', return_value=self.raw), \
                patch.object(server, 'gallery_add', return_value={'id': 'clean'}) as gallery:
            code, body = server.Handler.handle_remove_bg(Request(), {'image': self.data_url, 'method': 'none'})
        self.assertEqual(code, 200)
        self.assert_clean(base64.b64decode(body['image']))
        self.assertEqual(body['image'], gallery.call_args.args[0])
